# .github/workflows/trigger-gitlab-ci.yml
name: Trigger GitLab CI

on:
  pull_request:
    branches:
      - main
      - development
      - staging

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI
        uses: appleboy/gitlab-ci-trigger-action@master
        with:
          url: ${{ secrets.GITLAB_URL }}
          token: ${{ secrets.GITLAB_PAT }}
          project_id: ${{ secrets.GITLAB_PROJECT_ID }}
          ref: ${{ github.head_ref }}